defaults:
  - _self_

experiment_name: datacomp_experiment
data_path: /path/to/data

# Model configuration
model:
  name: CLIP
  variant: ViT-B-32

# Training configuration
train:
  batch_size: 256
  learning_rate: 1e-4
  num_epochs: 10

# Evaluation configuration
eval:
  datasets: [imagenet, pcam, cifar100]

# Filtering configuration
filter:
  use_general_filter: true
  task_specific:
    enabled: true
    target_task: imagenet  # Options: imagenet, cifar100, pcam, etc.
    use_trak: true
    use_clip_score: true
    use_neg_clip_loss: true
    trak_threshold: 0.5
    clip_score_threshold: 0.7
    neg_clip_loss_threshold: 0.3

# Privacy configuration
private: false
privacy_budget:
  epsilon: 1.0
  delta: 1e-5

# Optimization configuration
optim:
  n_trials: 100