hydra:
  mode: MULTIRUN
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: 1
    params:
      curation.ratio: choice(0.1, 0.2, 0.5, 0.75)
      curation.method: choice("template-text", "image-based", "linear-classifier", "random", "trak")
seed: 0
dry_run: false
dir_prefix: "curation"
output_dir: ${base_output_dir}/datacomp_v${seed}/
base_output_dir: "/raid/pdpl/small_clip_checkpoints/${dir_prefix}/${curation.method}/${curation.task}/ratio_${format_ratio:${curation.ratio}}"
s3_output_dir: "s3://pdpl/small_clip_checkpoints/${dir_prefix}/${curation.method}/${curation.task}/ratio_${format_ratio:${curation.ratio}}"
s3_endpoint_url: "https://s3.fraunhofer.de"
