hydra:
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: 1
    params:
      curation.ratio: range(0.1, 1.1, 0.1)
      curation.method: choice("template-text", "image-based", "linear-classifier")
      

gpu_id: 3
seed: 0
output_dir: ${base_output_dir}/datacomp_v${seed}/
curation:
  method: "template-text"
  task: "fitzpatrick17k"
  ratio: 0.5
base_output_dir: "/raid/pdpl/small_clip_checkpoints/curation/${curation.method}/${curation.task}/ratio_${curation.ratio}"
indistribution_data_tar: '/datasets/fitzpatrick17k/shards/fitzpatrick17k-train-{000000..000012}.tar'
indistribution_data_num_samples: 12858