defaults:
  - config
  - _self_
hydra:
  mode: MULTIRUN
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: 1
    params:
      curation.ratio: choice(0.1, 0.2, 0.5, 0.75)
      curation.method: choice("template-text", "image-based", "linear-classifier", "random")
      curation.task: choice( "pcam",  "fairvision/AMD", "food101", "cifar100") #"fmow", "resisc45", "fairvision/DR",  "fitzpatrick17k", "fairvision/Glaucoma",)

gpu_id: 3
dry_run: false 
curation:
  method: "template-text"
  task: "fitzpatrick17k"
  ratio: 0.5
  indistribution_data_tar: ${get_data_tar:${curation.task}}
